/**
* This is an autogenerated file created by the Stencil compiler.
* It contains typing information for all components that exist in this project.
*/
/* tslint:disable */

import '@stencil/core';




export namespace Components {

  interface OrkDatepicker {
    'name': string;
  }
  interface OrkDatepickerAttributes extends StencilHTMLAttributes {
    'name'?: string;
  }

  interface MyFirstComponent {
    'name': string;
  }
  interface MyFirstComponentAttributes extends StencilHTMLAttributes {
    'name'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'OrkDatepicker': Components.OrkDatepicker;
    'MyFirstComponent': Components.MyFirstComponent;
  }

  interface StencilIntrinsicElements {
    'ork-datepicker': Components.OrkDatepickerAttributes;
    'my-first-component': Components.MyFirstComponentAttributes;
  }


  interface HTMLOrkDatepickerElement extends Components.OrkDatepicker, HTMLStencilElement {}
  var HTMLOrkDatepickerElement: {
    prototype: HTMLOrkDatepickerElement;
    new (): HTMLOrkDatepickerElement;
  };

  interface HTMLMyFirstComponentElement extends Components.MyFirstComponent, HTMLStencilElement {}
  var HTMLMyFirstComponentElement: {
    prototype: HTMLMyFirstComponentElement;
    new (): HTMLMyFirstComponentElement;
  };

  interface HTMLElementTagNameMap {
    'ork-datepicker': HTMLOrkDatepickerElement
    'my-first-component': HTMLMyFirstComponentElement
  }

  interface ElementTagNameMap {
    'ork-datepicker': HTMLOrkDatepickerElement;
    'my-first-component': HTMLMyFirstComponentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
