/**
* This is an autogenerated file created by the Stencil compiler.
* It contains typing information for all components that exist in this project.
*/
/* tslint:disable */

import '@stencil/core';




export namespace Components {

  interface MyFirstComponent {
    'name': string;
  }
  interface MyFirstComponentAttributes extends StencilHTMLAttributes {
    'name'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'MyFirstComponent': Components.MyFirstComponent;
  }

  interface StencilIntrinsicElements {
    'my-first-component': Components.MyFirstComponentAttributes;
  }


  interface HTMLMyFirstComponentElement extends Components.MyFirstComponent, HTMLStencilElement {}
  var HTMLMyFirstComponentElement: {
    prototype: HTMLMyFirstComponentElement;
    new (): HTMLMyFirstComponentElement;
  };

  interface HTMLElementTagNameMap {
    'my-first-component': HTMLMyFirstComponentElement
  }

  interface ElementTagNameMap {
    'my-first-component': HTMLMyFirstComponentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
